# Generated by Django 2.0.4 on 2018-05-18 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mycomment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='thumb_down',
            field=models.ManyToManyField(related_name='comment_thumb_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='thumb_up',
            field=models.ManyToManyField(related_name='comment_thumb_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='head_comment',
            name='attention',
            field=models.ManyToManyField(related_name='head_comment_attention', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='head_comment',
            name='thumb_down',
            field=models.ManyToManyField(related_name='head_comment_thumb_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='head_comment',
            name='thumb_up',
            field=models.ManyToManyField(related_name='head_comment_thumb_up', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
